# Generated by Django 3.0.4 on 2020-03-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='words_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
                ('from_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atgapp.urls')),
            ],
        ),
    ]
