# Generated by Django 3.0.4 on 2020-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words_count',
            name='from_url',
            field=models.CharField(max_length=150),
        ),
    ]
