# Generated by Django 3.0.4 on 2020-03-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atgapp', '0002_auto_20200319_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words_count',
            old_name='from_url',
            new_name='fromurl',
        ),
    ]
